### ISSUE TITLE
Move to `extraHackages`

### ISSUE THREAD

**Issue by MangoIV** [mlabs-haskell/plutip#101]
- as we're moving away from `extraSources` to `extraHackages` from https://github.com/mlabs-haskell/haskell-nix-extra-hackage we should also do it here, to make it easier to include `plutip` as a dependency

**Comment by gege251** [comment]
The work has started here:
https://github.com/mlabs-haskell/bot-plutus-interface/pull/97

**Comment by MangoIV** [comment]
thank you, awesome!
