### ISSUE TITLE
User experience improvements

### ISSUE THREAD

**Issue by mikekeke** [mlabs-haskell/plutip#22]
Issue for aggregating/discussing/proposing UX improvements.

- [x] Assertions and integration with tasty #18 
- [ ] Action to send some Ada to already created wallet or create wallet with arbitrary number of UTxOs (e.g. if user need more that one UTxO with Ada to perform contract interactions)
- [x] Stabilizing public functions, add documentation and changelog
- [x] Custom configuration for the local cluster (and figuring out what we allow to be changed) #29

**Comment by MangoIV** [comment]
Hi! I thought this might be part of it: When pulling `master` and entering a development shell with `nix develop`, it starts building `ghc-8.6.5`. I have all the caches set up and this is hasn't been happening on any other repo until now. Is this expected?

**Comment by mikekeke** [comment]
@MangoIV No, it shouldn't be that way. It should download those things from cache. Could it be that cache is unavailable? (it happens sometimes)

**Comment by MangoIV** [comment]
Mmmh, would be strange, this is also not the first time I try and it always tries to build IOG's GHC fork. But if you say it didn't build it for you, then it might be still my fault, I will investigate further. Thanks!

**Comment by gege251** [comment]
Moved the remaining issue to #50
