### ISSUE TITLE
Output transaction + pab request logs with faulty contracts

### ISSUE THREAD

**Issue by bladyjoker** [mlabs-haskell/plutip#46]
Hi folks,

I added a first Plutip based test for the Cardax project and it works great. A couple of UX improvements would make it even better.

Specifically, when developing a contract and a test, it's important to be able to understand the flow of transactions and PAB requests as they lead up to a problematic state. It's a very useful feature of the `Plutus.Trace.Emulator`environment and it would be great if we can reproduce the feature with Plutip.

I'd be happy to contribute as well...

**Comment by bladyjoker** [comment]
Fyi at https://github.com/mlabs-haskell/plutip/blob/master/src/Test/Plutip/Internal/BotPlutusInterface/Run.hs#L107 switching to Debug gives you a pretty decent PAB request logging to stdout. Not ideal, but for starters we could expose this flag to `PlutipConfig` until we get a saner solution.

The saner solution imo would be to have proper logging framework used at bot-plutus-interface, configurable outputs so we can dump `pab.log` to user's screen in the case of a faulty test.

**Comment by zmrocze** [comment]
I've added this flag so now one can get PAB requests logged - bashed together with all the other logs.

So next step is definitely to make use of some logging framework as at this point there is few logging sources and few hacks to show/supress these.
