### ISSUE TITLE
General assertWith

### ISSUE THREAD

**Issue by bladyjoker** [mlabs-haskell/plutip#47]
Hey folks,

I found myself wanting a general

```haskell
assertWith ::  forall (w :: Type) (s :: Row Type) (e :: Type) (a :: Type).
  TestContractConstraints w s e a =>
  String ->
  TestWallets ->
  (a -> w -> NonEmpty Value -> Bool)
  ([PaymentPubKeyHash] -> Contract w s e a) ->
  (TestWallets, IO (ClusterEnv, NonEmpty BpiWallet) -> TestTree)
```

That allows me to combine state/result/value in a a test predicate.

**Comment by gege251** [comment]
Hey @bladyjoker ,
We've implemented a new feature to allow multiple assertions for a single contract [here](https://github.com/mlabs-haskell/plutip/pull/52).
I think this would make a general assertion unnecessary, so I closed this issue, but feel free to reopen it, if you feel like it's not enough for your use case!

**Comment by bladyjoker** [comment]
Looks pretty cool! Thanks a lot!
