### ISSUE TITLE
Documentation enhancement 	

### ISSUE THREAD

**Issue by mikekeke** [mlabs-haskell/plutip#78]
Plutip keeps getting new features, but some of them either not mentioned in README at all or not too visible.
Some of things that could be improved/mentioned listed below.

‼️~There will be significant changes in wallets initialization - see #104~ <-- work on this was pushed back

### Usage example
- [x] need to be updated, doesn't reflect current DSL

### Tasty integration
Mention key features:
- [x] assertions against result of contract execution
- [x] execution budget assertions for regression testing
- [x] upcoming tracing capabilities #77 

### Local cluster capabilities
Mention available use-cases:
- [x] launching private testnet for safe experiments with another tools from cardano ecosystem
- [x]  launching private testnet and setting up some funded wallets using eDSL, arbitrary contracts execution also possible
  - ~upcoming tracing capabilities (#77)  can be handy here as well; brief explanation of logs collecting~ <-- tracing works with contract execution, local cluster alone doesn't execute contracts

### Configuration
- [ ] provide some info on how things like slot length and max transaction budgets can be set up

### Caveats
- [x] Users should be aware about collateral handling mechanism if they want to use assertions on Values. Currently it is handled by `withCollateral` (see #100), but will change in future due to #104

### Pitfalls
- [x] note that each `assertExecution` in list of tests runs under same cluster - it creates new wallet(s) for each contract run, but if same validator is used in different  `assertExecution` calls, the address will stay same and whatever utxos created there will stay also - tests are not isolated in that sense

**Comment by cortsf** [comment]
Doc request: Explain the behavior of `withContractAs` with respect to `n` and `m`:

```
void $  withContractAs n $ [m] -> makeNftAsAdminContract
```

**Comment by IAmPara0x** [comment]
due to https://github.com/mlabs-haskell/plutip/issues/104, plutip will major changes in syntax of wallet initialization and contracts functions (such as `withContractAs`). Hence, imo we should hold off on adding docs for that part

**Comment by mikekeke** [comment]
@IAmPara0x thanks for pointing that out. I've updated description.
